name: 'BitWarden Env Variable Helper'
description: 'Greet someone'
inputs:
  bwkeys:  # id of input
    description: 'Keys'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - id: Run-export-variable-script
      run: |
        #echo $GITHUB_ACTION_PATH
        $GITHUB_ACTION_PATH/export-variables.sh "${{ inputs.bwkeys }}"
      shell: bash
    - id: bwkeys-print
      run: |
          IFS='|' read -ra arrIN <<< "${{ inputs.bwkeys }}"
          for i in "${arrIN[@]}"
          do
            :
            echo "$i"
            echo "$i"="oooooo" >> $GITHUB_ENV
            #echo "$i="$(bw list items --search $i | jq '.[0] | .notes' -r) >> $GITHUB_ENV
          done
      shell: bash
